- docker_container:
    name: filebeat
    image: docker.elastic.co/beats/filebeat:6.3.0
    detach: yes
    pull: no
    hostname: filebeat
    volumes: /root/ELK_on_DOCKER_with_ANSIBLE/roles/Filebeat/files/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,/var/lib/docker/containers:/hostfs/var/lib/docker/containers:ro
    env: LOG_LEVEL=DEBUG
    networks:
      - name: elk-network
