  - lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '.*ForwardToSyslog.*'
      line: 'ForwardToSyslog=yes'
      state: present

  - systemd:
      name: "{{ item }}"
      state: restarted
    with_items:
    - systemd-journald
    - rsyslog
