- docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:6.3.0
    detach: yes
    pull: no
    hostname: logstash
    volumes: /root/playbooks/roles/Logstash/files/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - name: elk-network
