- set_fact:
    logstash_conf: "{{ role_path }}/files/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"

- docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:6.3.0
    detach: yes
    pull: no
    hostname: logstash
    volumes:
      - "{{ logstash_conf }}"
    networks:
      - name: elk-network
