- docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:6.3.0
    detach: yes
    pull: no
    hostname: kibana
    volumes: /root/ELK_on_DOCKER_with_ANSIBLE/roles/Kibana/files/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - name: elk-network
