- docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    detach: yes
    pull: no
    hostname: elasticsearch
    published_ports: 9200:9200,9300:9300
    env: discovery.type=single-node
    networks:
      - name: elk-network
